apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: fernando
  annotations:
    backstage.io/techdocs-ref: value
spec:
  profile:
    displayName: Fernando Hernández Rodríguez
    email: fernando.b.hernandez@accenture.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [atc]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: fernando.b.hernandez@accenture.com
  annotations:
    backstage.io/techdocs-ref: value
spec:
  profile:
    displayName: Fernando Hernández Rodríguez
    email: fernando.b.hernandez@accenture.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [atc]
